spring:
  application:
    name: backend
  ai:
    vertex:
      ai:
        gemini:
          project-id: ${GEMINI_PROJECT_ID} # 구글 클라우드 프로젝트 ID
          location: us-central1        # 리전 설정
          chat:
            options:
              model: gemini-2.5-flash-lite
        embedding:
          project-id: ${GEMINI_PROJECT_ID}
          location: us-central1
          options:
            model: text-embedding-004
    vectorstore:
      qdrant:
        host: ${QDRANT_HOST}
        port: 6334
        api-key: ${QDRANT_API_KEY}
        use-tls: true
        collection-name: ${QDRANT_COLLECTION}
app:
  init-vector-store: false
  frontend:
    url: ${FRONTEND_URL:http://localhost:3000}